<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Subscriptions Assistant</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        .booksDisplay {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-evenly;
        }

        h2 {
            width: 15rem;
        }

        .eachBook {
            display: flex;
            flex-direction: column;
            padding: 10px;
        }
    </style>
</head>
<body>
<h1></h1>
<div class="booksDisplay"><?php
    foreach($booksArray as $book)
    {
        echo '<div class="eachBook">';
        echo '<h2>'.$book['title'].'</h2>';
        $imageURL = 'https://jackets.dmmserver.com/media/356/'. $book['image'] .'.jpg';
        echo "<img alt='book cover' src='$imageURL'>";
        echo '<p>Picks count: ' . $book['picksCount'] . '</p>';
        echo '</div>';
    }
    ?></div>
</body>
</html>
